# Site settings
title: brunocroh
description: Bruno Rodrigues - Full Stack Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bruno Rodrigues
user_description: Experienced full stack developer with 2+ years in web development and software engineering in general. I am not scared to tackle problems and I always find a solution. 
user_title: Full Stack Developer 
email: brunocroh@gmail.com
twitter_username: brunocroh
github_username:  brunocroh
gplus_username:  brunocroh

# Google-analytics
google-analytics:
  id: "UA-112759379-1"

exclude: ['package.json', 'src' , 'node_modules']
